## Origen de los datos.

### Covid-19 MÃ©xico.

https://datos.covid-19.conacyt.mx/#DownZCSV

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/josech/.local/lib/python3.10/site-packages (1.4.3)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.21.0 in /home/josech/.local/lib/python3.10/site-packages (from pandas) (1.23.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/josech/.local/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd

In [5]:
datos = pd.read_csv('data/Casos_Diarios_Estado_Nacional_Confirmados_20220906.csv')

In [6]:
datos

,cve_ent,poblacion,nombre,26-02-2020,27-02-2020,28-02-2020,29-02-2020,01-03-2020,02-03-2020,03-03-2020,...,27-08-2022,28-08-2022,29-08-2022,30-08-2022,31-08-2022,01-09-2022,02-09-2022,03-09-2022,04-09-2022,05-09-2022
0,1,1434635,AGUASCALIENTES,0,0,0,0,0,0,0,...,9,10,69,38,47,30,20,6,5,10
1,2,3634868,BAJA CALIFORNIA,0,0,0,0,0,0,0,...,32,26,181,130,133,90,75,19,10,68
2,3,804708,BAJA CALIFORNIA SUR,0,0,0,0,0,0,0,...,38,15,70,53,42,30,17,11,13,30
3,4,1000617,CAMPECHE,0,0,0,0,0,0,0,...,3,0,15,9,2,4,2,0,0,4
4,7,5730367,CHIAPAS,0,0,0,1,0,0,0,...,35,4,6,8,6,6,5,0,2,3
5,8,3801487,CHIHUAHUA,0,0,0,0,0,0,0,...,17,21,153,99,75,66,53,5,6,24
6,9,9018645,DISTRITO FEDERAL,0,2,0,0,0,0,1,...,209,163,591,520,402,399,348,144,128,255
7,5,3218720,COAHUILA,0,0,1,0,0,0,1,...,22,14,67,32,30,31,26,8,8,18
8,6,785153,COLIMA,0,0,0,0,0,0,0,...,12,10,20,11,17,6,6,4,12,10
9,10,1868996,DURANGO,0,0,0,0,0,0,0,...,4,4,21,17,24,14,7,3,2,7
10,11,6228175,GUANAJUATO,0,0,0,0,1,3,3,...,38,54,111,103,81,73,57,19,14,31
11,12,3657048,GUERRERO,0,0,0,0,0,0,0,...,8,10,26,21,18,12,19,3,3,7
12,13,3086414,HIDALGO,0,1,0,0,0,0,0,...,15,48,113,74,48,46,30,13,19,17
13,14,8409693,JALISCO,0,0,0,0,0,0,0,...,31,39,147,116,84,58,75,23,22,41
14,15,17427790,MEXICO,0,1,1,1,0,2,2,...,63,47,282,209,208,164,119,26,33,98
15,16,4825401,MICHOACAN,0,0,0,0,0,0,0,...,20,11,58,52,41,35,19,3,9,10
16,17,2044058,MORELOS,0,0,0,0,0,0,0,...,9,7,28,42,31,54,8,3,5,6
17,18,1288571,NAYARIT,0,0,0,0,0,0,1,...,2,7,33,24,23,13,14,7,11,11
18,19,5610153,NUEVO LEON,0,0,0,0,0,0,0,...,42,55,162,153,106,94,88,17,14,41
19,20,4143593,OAXACA,0,0,0,0,1,0,0,...,14,20,45,37,28,31,42,11,15,24
20,21,6604451,PUEBLA,0,0,0,0,0,0,0,...,41,33,88,90,67,76,57,14,24,24
21,22,2279637,QUERETARO,0,0,0,0,0,0,0,...,14,15,80,74,51,44,27,8,6,28
22,23,1723259,QUINTANA ROO,0,0,0,0,0,0,0,...,12,6,21,16,22,11,11,11,8,10
23,24,2866142,SAN LUIS POTOSI,0,0,0,0,0,0,0,...,61,27,196,112,174,92,87,30,10,58
24,25,3156674,SINALOA,0,0,0,0,0,0,0,...,56,56,82,67,77,76,63,43,36,22
25,26,3074745,SONORA,0,0,0,0,0,0,0,...,23,26,113,119,94,74,47,17,15,66
26,27,2572287,TABASCO,0,0,0,0,0,0,0,...,6,5,33,20,18,17,12,6,3,16
27,28,3650602,TAMAULIPAS,0,0,0,0,0,0,0,...,17,11,110,70,66,69,47,13,11,44
28,29,1380011,TLAXCALA,0,0,0,0,0,0,0,...,14,14,43,25,19,14,18,5,4,7
29,30,8539862,VERACRUZ,0,0,0,0,0,0,0,...,21,28,60,53,46,33,26,9,12,17
30,31,2259098,YUCATAN,0,0,0,0,0,0,0,...,8,11,50,24,27,27,31,2,5,42
31,32,1666426,ZACATECAS,0,0,0,0,0,0,1,...,8,10,45,33,36,21,27,7,11,22
32,0,127792286,Nacional,0,4,2,2,2,5,9,...,904,807,3119,2451,2143,1810,1483,490,476,1071

In [7]:
datos = datos.transpose()[2:]

In [8]:
datos

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
nombre,AGUASCALIENTES,BAJA CALIFORNIA,BAJA CALIFORNIA SUR,CAMPECHE,CHIAPAS,CHIHUAHUA,DISTRITO FEDERAL,COAHUILA,COLIMA,DURANGO,...,SAN LUIS POTOSI,SINALOA,SONORA,TABASCO,TAMAULIPAS,TLAXCALA,VERACRUZ,YUCATAN,ZACATECAS,Nacional
26-02-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27-02-2020,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,4
28-02-2020,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,2
29-02-2020,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
01-09-2022,30,90,30,4,6,66,399,31,6,14,...,92,76,74,17,69,14,33,27,21,1810
02-09-2022,20,75,17,2,5,53,348,26,6,7,...,87,63,47,12,47,18,26,31,27,1483
03-09-2022,6,19,11,0,0,5,144,8,4,3,...,30,43,17,6,13,5,9,2,7,490
04-09-2022,5,10,13,0,2,6,128,8,12,2,...,10,36,15,3,11,4,12,5,11,476
05-09-2022,10,68,30,4,3,24,255,18,10,7,...,58,22,66,16,44,7,17,42,22,1071

In [9]:
datos.columns = pd.Index(datos.iloc[0])

In [10]:
datos

nombre,AGUASCALIENTES,BAJA CALIFORNIA,BAJA CALIFORNIA SUR,CAMPECHE,CHIAPAS,CHIHUAHUA,DISTRITO FEDERAL,COAHUILA,COLIMA,DURANGO,...,SAN LUIS POTOSI,SINALOA,SONORA,TABASCO,TAMAULIPAS,TLAXCALA,VERACRUZ,YUCATAN,ZACATECAS,Nacional
nombre,AGUASCALIENTES,BAJA CALIFORNIA,BAJA CALIFORNIA SUR,CAMPECHE,CHIAPAS,CHIHUAHUA,DISTRITO FEDERAL,COAHUILA,COLIMA,DURANGO,...,SAN LUIS POTOSI,SINALOA,SONORA,TABASCO,TAMAULIPAS,TLAXCALA,VERACRUZ,YUCATAN,ZACATECAS,Nacional
26-02-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27-02-2020,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,4
28-02-2020,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,2
29-02-2020,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
01-09-2022,30,90,30,4,6,66,399,31,6,14,...,92,76,74,17,69,14,33,27,21,1810
02-09-2022,20,75,17,2,5,53,348,26,6,7,...,87,63,47,12,47,18,26,31,27,1483
03-09-2022,6,19,11,0,0,5,144,8,4,3,...,30,43,17,6,13,5,9,2,7,490
04-09-2022,5,10,13,0,2,6,128,8,12,2,...,10,36,15,3,11,4,12,5,11,476
05-09-2022,10,68,30,4,3,24,255,18,10,7,...,58,22,66,16,44,7,17,42,22,1071

In [11]:
datos = datos[1:]

In [12]:
datos

nombre,AGUASCALIENTES,BAJA CALIFORNIA,BAJA CALIFORNIA SUR,CAMPECHE,CHIAPAS,CHIHUAHUA,DISTRITO FEDERAL,COAHUILA,COLIMA,DURANGO,...,SAN LUIS POTOSI,SINALOA,SONORA,TABASCO,TAMAULIPAS,TLAXCALA,VERACRUZ,YUCATAN,ZACATECAS,Nacional
26-02-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27-02-2020,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,4
28-02-2020,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,2
29-02-2020,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
01-03-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
01-09-2022,30,90,30,4,6,66,399,31,6,14,...,92,76,74,17,69,14,33,27,21,1810
02-09-2022,20,75,17,2,5,53,348,26,6,7,...,87,63,47,12,47,18,26,31,27,1483
03-09-2022,6,19,11,0,0,5,144,8,4,3,...,30,43,17,6,13,5,9,2,7,490
04-09-2022,5,10,13,0,2,6,128,8,12,2,...,10,36,15,3,11,4,12,5,11,476
05-09-2022,10,68,30,4,3,24,255,18,10,7,...,58,22,66,16,44,7,17,42,22,1071

In [13]:
datos = datos.astype(int)

In [14]:
datos.reset_index(inplace=True)

In [15]:
datos

nombre,index,AGUASCALIENTES,BAJA CALIFORNIA,BAJA CALIFORNIA SUR,CAMPECHE,CHIAPAS,CHIHUAHUA,DISTRITO FEDERAL,COAHUILA,COLIMA,...,SAN LUIS POTOSI,SINALOA,SONORA,TABASCO,TAMAULIPAS,TLAXCALA,VERACRUZ,YUCATAN,ZACATECAS,Nacional
0,26-02-2020,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,27-02-2020,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,4
2,28-02-2020,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,2
3,29-02-2020,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
4,01-03-2020,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,01-09-2022,30,90,30,4,6,66,399,31,6,...,92,76,74,17,69,14,33,27,21,1810
919,02-09-2022,20,75,17,2,5,53,348,26,6,...,87,63,47,12,47,18,26,31,27,1483
920,03-09-2022,6,19,11,0,0,5,144,8,4,...,30,43,17,6,13,5,9,2,7,490
921,04-09-2022,5,10,13,0,2,6,128,8,12,...,10,36,15,3,11,4,12,5,11,476
922,05-09-2022,10,68,30,4,3,24,255,18,10,...,58,22,66,16,44,7,17,42,22,1071

In [16]:
datos['index'] = pd.to_datetime(datos['index'], format="%d-%m-%Y")

In [24]:
datos.loc['index']

KeyError: 'index'

In [18]:
datos.set_index('index', inplace=True)

In [20]:
datos["index" > "2020"]

KeyError: True

https://parquet.apache.org/

In [ ]:
!pip install pyarrow

In [ ]:
datos.to_parquet('data/data_covid.parquet')

In [ ]:
datos.to_csv('data/data_covid.csv')

In [ ]:
datos.to_json('data/data_covid.json', indent=True)

In [ ]:
pd.read_json('data/data_covid.json')

In [ ]:
import seaborn as sb

In [ ]:
sb.lineplot(x=datos.index, y=datos['Nacional'])

## CÃ¡lculo de promedios.

```SQL
WITH promedios AS
 (SELECT 2020 as Anio, ROUND(AVG(Nacional), 2) as promedio 
  FROM `bigquery-demo-349123.demo.covid`
  WHERE index BETWEEN TIMESTAMP('2020-01-01') AND TIMESTAMP('2020-12-31')
```

```SQL
WITH promedios AS
 (SELECT 2020 as Anio, ROUND(AVG(Nacional), 2) as promedio 
  FROM `bigquery-demo-349123.demo.covid`
  WHERE index BETWEEN TIMESTAMP('2020-01-01') AND TIMESTAMP('2020-12-31')
  UNION ALL
  SELECT 2021, ROUND(AVG(Nacional), 2)
  FROM `bigquery-demo-349123.demo.covid`
  WHERE index BETWEEN TIMESTAMP('2021-01-01') AND TIMESTAMP('2021-12-31')
  UNION ALL
  SELECT 2022, ROUND(AVG(Nacional), 2)
  FROM `bigquery-demo-349123.demo.covid`
  WHERE index BETWEEN TIMESTAMP('2022-01-01') AND TIMESTAMP('2022-12-31'))
SELECT * FROM promedios
```

## Datos de 2022. Nacional y Distrito Federal.

``` SQL
SELECT index, Nacional
FROM `bigquery-demo-349123.demo.covid`
WHERE EXTRACT(YEAR AS index) = 2022
ORDER BY index;
```